defaults:
  - data: basic_multilabel
  - model: tabfusion
  - experiment: experiment
  - evaluation: eval
  - override hydra/sweeper: optuna
    
hydra:
  sweeper:
    sampler:
      seed: 123
    direction: maximize
    study_name: train_model
    storage: null
    n_trials: 100
    n_jobs: 1
    params:
      data.bs: choice(256,512)
      data.min_seq_len: range(5,10, step=1)
      #data.undersampling: range(0.0,0.3, step=0.1)
      data.cut_off_col_idx: choice(10, 20)
      data.bin_freq: choice("30S", "1Min")
      data.bin_operation: choice("min", "max", "mean")
      model.fc_dropout: range(0.0, 0.9, step=0.1)
      model.res_dropout: range(0.0, 0.9, step=0.1)
      model.d_model: choice(32,64,128)
      model.n_layers: choice(2,6,8,10)
      model.n_heads: choice(2,4,8,16)
      model.lr_factor: range(0.5, 1.0, step= 0.1)
      model.weights: choice(True, False)
      model.weights_factor: range(0.1, 1.0, step=0.1)

# 5 minutes max